---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
      require_chef_omnibus: true
      customize:
         memory: 512
#  - name: centos-6.4


suites:
  - name: default
    run_list:
      - recipe[symfony::default]
    attributes:
      mysql:
        server_root_password: rootpass
        server_debian_password: debpass
        server_repl_password: replpass
      symfony:
        database:
          password: myapp_1234
          name: symfony
          user: symfony
        projects:
          - { domain: 'symfony-app.dev', document_root: '/var/sites/symfony-app.dev/web', remove_trailing_slash: false }