name             'symfony'
maintainer       'Dmitry Tsoy'
maintainer_email 'hd.deman@gmail.com'
license          'All rights reserved'
description      'Deploys and configures Symfony-based applications'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '2.0.6'

depends 'nginx', '~> 2.7.0'
depends 'php-fpm', '~> 0.6.8'
depends 'php', '~> 1.4.6'
depends 'mysql', '~> 5.1.8'
depends 'database', '~> 2.1.6'
depends 'rbenv', '~> 1.6.5'
depends 'git', '~> 4.0.2'
depends 'composer', '~> 1.0.0'
